# Generated by Django 3.2.7 on 2021-09-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PcPeripherals', '0002_auto_20210923_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
