# Generated by Django 3.2.5 on 2021-09-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PcPeripherals', '0007_auto_20210924_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_img/profile.png', null=True, upload_to='profile_img/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
